In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('tennis.csv')

In [11]:
df = df.iloc[:,1:]

In [12]:
df.sample(5)

     Outlook  Temperature  Humidity  Wind  PlayTennis
136      1.0          1.0       0.0   1.0           0
107      1.0          0.0       1.0   0.0           0
55       2.0          1.0       1.0   1.0           1
79       0.0          2.0       1.0   0.0           0
34       2.0          1.0       0.0   0.0           0

In [13]:
df.iloc[:,:-1].describe()

          Outlook  Temperature    Humidity        Wind
count  181.000000   181.000000  181.000000  181.000000
mean     1.082873     1.038674    0.519337    0.596685
std      0.787954     0.825730    0.501012    0.491924
min      0.000000     0.000000    0.000000    0.000000
25%      0.000000     0.000000    0.000000    0.000000
50%      1.000000     1.000000    1.000000    1.000000
75%      2.000000     2.000000    1.000000    1.000000
max      2.000000     2.000000    1.000000    1.000000

In [17]:
temp = df.iloc[:,1].value_counts()

In [18]:
temp

Temperature
2.0    65
1.0    58
0.0    58
Name: count, dtype: int64

In [35]:
temp[2]

np.int64(65)

In [20]:
out = df.iloc[:,0].value_counts()

In [22]:
out

Outlook
1.0    68
2.0    64
0.0    49
Name: count, dtype: int64

In [23]:
humid = df.iloc[:,2].value_counts()

In [24]:
humid

Humidity
1.0    94
0.0    87
Name: count, dtype: int64

In [25]:
wind = df.iloc[:,3].value_counts()

In [26]:
wind

Wind
1.0    108
0.0     73
Name: count, dtype: int64

In [29]:
plyt = df.iloc[:,-1].value_counts()

In [30]:
plyt

PlayTennis
1    105
0     76
Name: count, dtype: int64

In [33]:
print(f"out:{len(out)}, temp:{len(temp)}, humid:{len(humid)}, wind:{len(wind)}")

out:3, temp:3, humid:2, wind:2

In [34]:
# plyt -> has 2 condition 1, 0

In [37]:
a = 1
b = 2
c = 1
d = 0

In [39]:
win_prob = out[a]/plyt[1]*temp[b]/plyt[1]*humid[c]/plyt[1]*wind[d]/plyt[1]
win_prob

np.float64(0.2495259896853677)

In [40]:
lose_prob = out[a]/plyt[0]*temp[b]/plyt[0]*humid[c]/plyt[0]*wind[d]/plyt[0]
lose_prob

np.float64(0.9091145613523529)