In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# unzip archive.zip
"""
loan_test.csv
loan_train.csv
"""
df = pd.read_csv('loan_train.csv')

In [4]:
df[df.duplicated()].sum()

Gender                  0
Married                 0
Dependents              0
Education               0
Self_Employed           0
Applicant_Income        0
Coapplicant_Income    0.0
Loan_Amount             0
Term                  0.0
Credit_History        0.0
Area                    0
Status                  0
dtype: object

In [5]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              601 non-null    object
 1   Married             611 non-null    object
 2   Dependents          599 non-null    object
 3   Education           614 non-null    object
 4   Self_Employed       582 non-null    object
 5   Applicant_Income    614 non-null    int64
 6   Coapplicant_Income  614 non-null    float64
 7   Loan_Amount         614 non-null    int64
 8   Term                600 non-null    float64
 9   Credit_History      564 non-null    float64
 10  Area                614 non-null    object
 11  Status              614 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 57.7+ KB

In [7]:
df.isnull().sum()

Gender                13
Married                3
Dependents            15
Education              0
Self_Employed         32
Applicant_Income       0
Coapplicant_Income     0
Loan_Amount            0
Term                  14
Credit_History        50
Area                   0
Status                 0
dtype: int64

In [8]:
df.shape

(614, 12)

In [9]:
5000/614

8.143322475570033

In [10]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Term',
       'Credit_History', 'Area', 'Status'],
      dtype='object')

In [11]:
col = df.columns[df.isnull().any()]

In [12]:
col_df = df[col]

In [13]:
col_df.dropna()

     Gender Married Dependents Self_Employed   Term  Credit_History
0      Male      No          0            No  360.0             1.0
1      Male     Yes          1            No  360.0             1.0
2      Male     Yes          0           Yes  360.0             1.0
3      Male     Yes          0            No  360.0             1.0
4      Male      No          0            No  360.0             1.0
..      ...     ...        ...           ...    ...             ...
609  Female      No          0            No  360.0             1.0
610    Male     Yes         3+            No  180.0             1.0
611    Male     Yes          1            No  360.0             1.0
612    Male     Yes          2            No  360.0             1.0
613  Female      No          0           Yes  360.0             0.0

[499 rows x 6 columns]

In [14]:
df = df.dropna()

In [15]:
df.sample(5)

,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
179,Male,No,0,Not Graduate,No,233300,145100.0,10200000,480.0,0.0,Urban,N
609,Female,No,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
581,Male,No,0,Graduate,No,183600,3383700.0,9000000,360.0,1.0,Urban,N
119,Female,No,0,Graduate,No,1040800,0.0,25900000,360.0,1.0,Urban,Y
92,Male,Yes,2,Not Graduate,No,327300,182000.0,8100000,360.0,1.0,Urban,Y

In [16]:
df.shape

(499, 12)

In [17]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [18]:
oe = OneHotEncoder()
transformed = oe.fit_transform(df[['Gender', 'Married','Education', 'Self_Employed', "Area"]])

In [19]:
transformed.toarray()

array([[0., 1., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.]], shape=(499, 11))

In [20]:
oe.feature_names_in_

array(['Gender', 'Married', 'Education', 'Self_Employed', 'Area'],
      dtype=object)

In [21]:
oe.get_feature_names_out()

array(['Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes',
       'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No',
       'Self_Employed_Yes', 'Area_Rural', 'Area_Semiurban', 'Area_Urban'],
      dtype=object)

In [22]:
dfs = pd.DataFrame(transformed.toarray())

In [23]:
dfs.columns = oe.get_feature_names_out()

In [24]:
dfs

,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Area_Rural,Area_Semiurban,Area_Urban
0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
494,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
495,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
496,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
497,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
498,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [25]:
in_col = oe.feature_names_in_

In [26]:
cols = list(set(df.columns) - set(in_col))
cols

['Credit_History',
 'Term',
 'Coapplicant_Income',
 'Status',
 'Dependents',
 'Applicant_Income',
 'Loan_Amount']

In [27]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Term',
       'Credit_History', 'Area', 'Status'],
      dtype='object')

In [28]:
col = df[cols]

In [29]:
df.merge(dfs, col, on="id", how="outer")

TypeError: DataFrame.merge() got multiple values for argument 'how'

In [30]:
col

,Credit_History,Term,Coapplicant_Income,Status,Dependents,Applicant_Income,Loan_Amount
0,1.0,360.0,0.0,Y,0,584900,15000000
1,1.0,360.0,150800.0,N,1,458300,12800000
2,1.0,360.0,0.0,Y,0,300000,6600000
3,1.0,360.0,235800.0,Y,0,258300,12000000
4,1.0,360.0,0.0,Y,0,600000,14100000
...,...,...,...,...,...,...,...
609,1.0,360.0,0.0,Y,0,290000,7100000
610,1.0,180.0,0.0,Y,3+,410600,4000000
611,1.0,360.0,24000.0,Y,1,807200,25300000
612,1.0,360.0,0.0,Y,2,758300,18700000
613,0.0,360.0,0.0,N,0,458300,13300000

In [32]:
dfs.shape

(499, 11)

In [35]:
col.shape

(499, 7)

In [43]:
dfs['a'] = col['Credit_History'].values

In [44]:
col.columns

Index(['Credit_History', 'Term', 'Coapplicant_Income', 'Status', 'Dependents',
       'Applicant_Income', 'Loan_Amount'],
      dtype='object')

In [45]:
dfs.shape

(499, 12)

In [46]:
dfs.isnull().sum()

Gender_Female             0
Gender_Male               0
Married_No                0
Married_Yes               0
Education_Graduate        0
Education_Not Graduate    0
Self_Employed_No          0
Self_Employed_Yes         0
Area_Rural                0
Area_Semiurban            0
Area_Urban                0
a                         0
dtype: int64

In [42]:
col['Credit_History'].isnull().sum()

np.int64(0)

In [47]:
col

,Credit_History,Term,Coapplicant_Income,Status,Dependents,Applicant_Income,Loan_Amount
0,1.0,360.0,0.0,Y,0,584900,15000000
1,1.0,360.0,150800.0,N,1,458300,12800000
2,1.0,360.0,0.0,Y,0,300000,6600000
3,1.0,360.0,235800.0,Y,0,258300,12000000
4,1.0,360.0,0.0,Y,0,600000,14100000
...,...,...,...,...,...,...,...
609,1.0,360.0,0.0,Y,0,290000,7100000
610,1.0,180.0,0.0,Y,3+,410600,4000000
611,1.0,360.0,24000.0,Y,1,807200,25300000
612,1.0,360.0,0.0,Y,2,758300,18700000
613,0.0,360.0,0.0,N,0,458300,13300000

In [49]:
dfs

,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Area_Rural,Area_Semiurban,Area_Urban,a
0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
1,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0
4,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
494,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
495,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
496,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
497,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
498,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0